### PR TITLE
Sync libbpf to latest upstream

### PR DESCRIPTION
**Pull request by chaudron**

### CODE REVIEW

**Comment by tohojo** [comment]
Hmm, actually I'd prefer to keep this repo identical with upstream. So I'll close this and just push a straight fast-forward :)

**Comment by tohojo** [comment]
...which it seems I failed to do last time, so that'll have to be a force push :/

**Comment by chaudron** [comment]
Force push is fine, but don't forget to update xdp-tools, as it's probably using a missing reference?

Is there a specific reason why we do not link to libbpf/libbpf directly?

**Comment by tohojo** [comment]
Eelco Chaudron <notifications@github.com> writes:

> Force push is fine, but don't forget to update xdp-tools, as it's
> probably using a missing reference?

Yeah, kept the old reference in a separate branch for that reason
exactly :)

> Is there a specific reason why we do not link to libbpf/libbpf
> directly?

Because when prototyping new features it is sometimes useful to add
patches on top of libbpf (in a separate branch in this repo) and refer
to those in xdp-tools. When we mirror the whole repo we can do that by
just changing the submodule ref ID without having to change the URL.

**Comment by chaudron** [comment]
> Because when prototyping new features it is sometimes useful to add patches on top of libbpf (in a separate branch in this repo) and refer to those in xdp-tools. When we mirror the whole repo we can do that by just changing the submodule ref ID without having to change the URL.

Makes sense, thanks for clarifying!

**Pull request closed without merging**
